export { default as Home } from './List'
export { default as HomeDetail } from './Detail'
export { default as HomeTable } from './Table'
export { default as HomeAdd } from './New'
export { default as HomeUserDetail } from './UserDetail'
export { default as HomePef } from './private-component/PDFView'